version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config: 
      config: .eslintrc.json
    checks:
      compat/compat:
        enabled: false  
exclude_patterns:
  - "config/"
  - "dist/"
  - "docs/"
  - "utl/"
  - "test/"
  - "**/node_modules/"
  - "**/*.d.ts"
  - "src/parse/*parser.js"
  - "src/render/**/*.template.js"
  - "webpack.config.js"