image: node:latest

cache:
  paths:
  - node_modules/

test_async_node_latest:
  image: node:latest
  cache:
    paths:
    - node_modules/
  script:
   - npm install
   - npm run lint
   - npm run nsp
   - npm run test:cover
  except:
   - tags

test_async_node_8:
  image: node:8
  cache:
    paths:
    - node_modules/
  script:
   - npm install
   - npm run lint
   - npm run nsp
   - npm run test:cover
  except:
   - tags

test_async_node_6:
  image: node:6
  cache:
    paths:
    - node_modules/
  script:
   - npm install
   - npm run lint
   - npm run nsp
   - npm run test:cover
  except:
   - tags

pages:
  script:
   - make pages
  artifacts:
    paths:
     - public
  only:
    - tags
  except:
    - branches
