image: node:latest

cache:
  key: "$CI_JOB_NAME"
  untracked: true

test_async_node_latest:
  image: node:latest
  script:
   - npm install
   - npm run depcruise
   - npm run lint
   - npm run nsp
   - npm run test:cover
  except:
   - tags

test_async_node_8:
  image: node:8
  script:
   - npm install
   - npm run depcruise
   - npm run lint
   - npm run nsp
   - npm run test:cover
  except:
   - tags

test_async_node_6:
  image: node:6
  script:
   - npm install
   - npm run depcruise
   - npm run lint
   - npm run nsp
   - npm run test:cover
  except:
   - tags

pages:
  script:
   - make pages
  artifacts:
    paths:
     - public
  only:
    - tags
  except:
    - branches
