image: node:latest

cache:
  paths:
  - node_modules/

test_async:
  script:
   - npm install
   - npm run lint
   - npm run nsp
   - npm run cover

pages:
  script:
   - make pages
  artifacts:
    paths:
     - public
  # only:
   # - tags
  except:
   - branches
