sudo: false

language: node_js

node_js:
# temporarily disable node 6 builds - there's a weird, dependency-cruiser
# unrelated thing where npm installing breaks on there - something with
# nyc and babel parser
#  - "6"
  - "8"
  - "10"

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run depcruise
  - npm run lint
  - npm run nsp
  - npm run test:cover

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  directories:
    - node_modules
