sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "10"

install:
  - npm install

before_script:
  - 'if test `node --version | cut -c 2` = 10; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi'
  - 'if test `node --version | cut -c 2` = 10; then chmod +x ./cc-test-reporter; fi'
  - 'if test `node --version | cut -c 2` = 10; then ./cc-test-reporter before-build; fi'

script:
  - npm run depcruise
  - npm run lint
  - npm run nsp
  - npm run test:cover

after_script:
  - 'if test `node --version | cut -c 2` = 10; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi'

cache:
  directories:
    - node_modules
